
CFLAGS       = -fPIC
LDFLAGS      = -shared

all: scipy_a scipy_b athenb bthena

scipy_a: scipy_a.o
	$(CC) -o scipy_a.so scipy_a.o $(CFLAGS) $(LDFLAGS)

scipy_b: scipy_b.o
	$(CC) -o scipy_b.so scipy_b.o $(CFLAGS) $(LDFLAGS)

athenb: athenb.o
	$(CC) -o athenb athenb.o scipy_a.so scipy_b.so -Wl,-rpath .

bthena: bthena.o
	$(CC) -o bthena bthena.o scipy_b.so scipy_a.so -Wl,-rpath .
